services:

  cr8_system:
    build:
      context: .
    container_name: cr8_system
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - cr8_db
    networks:
      - app-network

  cr8_db:
    image: postgres:latest
    container_name: cr8_db
    env_file: 
      - .env
    networks:
      - app-network
    volumes: 
      - db_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
