# Generated by Django 3.2.9 on 2022-02-12 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20211210_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='user',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='print',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='print',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.BigIntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
                ('print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.print')),
            ],
        ),
    ]
